Playground with pandas

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
dates = pd.date_range('20130101', periods=6)

In [3]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [4]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01 -0.767494  0.566085  0.219308 -0.557441
2013-01-02 -0.425048 -0.246769  1.586751 -0.100451
2013-01-03  0.412057 -1.271223  1.498119 -1.463487
2013-01-04 -0.426442 -0.797006  0.005562 -1.787328
2013-01-05  0.875165  0.361260 -1.630808  0.736371
2013-01-06  0.340631 -0.044283  0.474139 -0.529146

In [5]:
df2 = pd.DataFrame({
     "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
})

df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [6]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [7]:
df.head()

                   A         B         C         D
2013-01-01 -0.767494  0.566085  0.219308 -0.557441
2013-01-02 -0.425048 -0.246769  1.586751 -0.100451
2013-01-03  0.412057 -1.271223  1.498119 -1.463487
2013-01-04 -0.426442 -0.797006  0.005562 -1.787328
2013-01-05  0.875165  0.361260 -1.630808  0.736371

In [8]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [9]:
df.loc[dates[0]]

A   -0.767494
B    0.566085
C    0.219308
D   -0.557441
Name: 2013-01-01 00:00:00, dtype: float64

In [10]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])